name: "test-windows"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-2019
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
        
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Install and prepare
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install holochain_cli --version 0.1.3 --locked
          cargo install holochain --version 0.1.3 --locked
          cargo install --version 0.2.3 lair_keystore --locked
          
      - name: install and test
        run: |
          npm i && npm t

